name: "Build tests"

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - "**.yml"
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Detect Node version
        run: echo "NODE_VERSION=$(cat .nvmrc)" >> $GITHUB_OUTPUT
        id: nvmrc

      - name: Use Node.js ${{ steps.nvmrc.outputs.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.nvmrc.outputs.NODE_VERSION }}"

      - name: Install dependencies
        run: |
          npm install

      - name: Lint, test, build
        run: |
          npm run all

      - name: Save Action Artifact
        uses: actions/upload-artifact@v3
        with:
          retention-days: 1
          name: release-artifact
          path: |
            ./dist
            action.yml
            package.json
            !dist/utils
            !dist/types

  basic:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - name: Download Action Artifact
        uses: actions/download-artifact@v3
        with:
          name: release-artifact
          path: ./

      - name: Display structure of downloaded files
        run: ls -R

      - name: Get information
        uses: ./
        id: get-information
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

